server:
  port: ${PORT:8080}
spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
  datasource:
    url: ${BOOK_ROOM_QUARTO_SPRING_DATASOURCE_URL:}
    username: ${BOOK_ROOM_QUARTO_SPRING_DATASOURCE_USERNAME:}
    password: ${BOOK_ROOM_QUARTO_SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  profiles:
    active: ${PROFILE_ENVIRONMENT:}
    include: actuator, springdoc, app