spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    br:
      com:
        book:
          room:
            quarto: debug
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG

server:
  error:
    include-stacktrace: always