server:
  port: ${PORT:8082}

spring:
  application:
    name: @project.name@
    description: @project.version@
    version: @project.description@
  datasource:
    url: ${BOOK_ROOM_RESERVA_SPRING_DATASOURCE_URL:}
    username: ${BOOK_ROOM_RESERVA_SPRING_DATASOURCE_USERNAME:}
    password: ${BOOK_ROOM_RESERVA_SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  profiles:
    active: ${PROFILE_ENVIRONMENT:dev}
    include: actuator, springdoc

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: d30f04c1bd0a63
    password: 56a421801f7c56
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true